create table cf_employees_addresses (
    id                             number generated by default on null as identity 
                                   constraint cf_employee_addres_id_pk primary key,
    employee_id                    number
                                   constraint cf_employee_add_employee_id_fk
                                   references cf_employees on delete cascade,
    street                         varchar2(100 char),
    house_number                   varchar2(100 char),
    bus_number                     varchar2(100 char),
    zipcode                        varchar2(100 char),
    city                           varchar2(100 char),
    country                        VARCHAR2(50 CHAR),
    telephone                      varchar2(25 char),
    created_on                     date not null,
    created_by                     varchar2(255 char) not null,
    modified_on                    date not null,
    modified_by                    varchar2(255 char) not null
)
;

create index cf_employees_addres_i1 on cf_employees_addresses (employee_id);