create table cf_performance_reviews (
    id                             number generated by default on null as identity 
                                   constraint cf_performance_rev_id_pk primary key,
    employee_id                    number
                                   constraint cf_performance_employee_id_fk
                                   references cf_employees on delete cascade,
    review_type                    number
                                   constraint cf_perf_rev_review_type_fk
                                   references cf_lov_values,
    employee_type                  number 
                                   constraint cf_perf_rev_employee_type_fk
                                   references cf_lov_values,
    coordinator_id                 varchar2(4000 char),
    start_date                     date,
    end_date                       date,
    report                         blob,
    approval_employee              number constraint cf_performanc_approval_empl_ck
                                   check (approval_employee IS NULL OR approval_employee in (0,1)),
    employe_approved_on            date,
    approval_coordinator           number constraint cf_performanc_approval_coor_ck
                                   check (approval_coordinator IS NULL OR approval_coordinator in (0,1)),
    coordinator_approved_on        date,
    coordinator_approved_by        varchar2(100char),                            
    created_on                     date not null,
    created_by                     varchar2(255 char) not null,
    modified_on                    date not null,
    modified_by                    varchar2(255 char) not null
)
;

create index cf_performance_rev_i1 on cf_performance_reviews (employee_id);