ALTER TABLE CF_STARTERS_EMPLOYEES
RENAME TO CF_EMPLOYEES;

ALTER TABLE CF_EMPLOYEES
ADD ( 
    USER_MGM_ID VARCHAR2(500) NOT NULL,
    LANGUAGE NUMBER,
    START_DATE DATE,
    OFFBOARDING_DATE DATE,
    BIRTHDATE DATE,
    FOREIGN KEY (LANGUAGE)
    REFERENCES CF_LOV_VALUES(ID)
); 