ALTER TABLE CF_STARTERS ADD (
  BUS_NUMBER VARCHAR2(20) 
);

ALTER TABLE CF_STARTERS 
RENAME COLUMN ADDRESS_LINE_1 TO STREET;

ALTER TABLE CF_STARTERS 
RENAME COLUMN ADDRESS_LINE_2 TO HOUSE_NUMBER;

ALTER TABLE CF_STARTERS MODIFY (
  HOUSE_NUMBER VARCHAR2(20 CHAR),
  ZIPCODE VARCHAR(10)
);