create table cf_tasks (
    id                             number generated by default on null as identity 
                                   constraint cf_tasks_id_pk primary key,
    employee_id                    number
                                   constraint cf_tasks_employee_id_fk
                                   references cf_employees on delete cascade,
    task_prio                      number,
    task                           varchar2(500 char),
    remarks                        varchar2(4000 char),
    completed_on                   date,
    created_on                     date not null,
    created_by                     varchar2(255 char) not null,
    modified_on                    date not null,
    modified_by                    varchar2(255 char) not null
)
;

create index cf_tasks_i1 on cf_tasks (employee_id);