create table cf_trainings_wishlist (
    id                             number generated by default on null as identity 
                                   constraint cf_trainings_wishl_id_pk primary key,
    employee_id                    number
                                   constraint cf_trainings_wi_employee_id_fk
                                   references cf_employees on delete cascade,
    title                          varchar2(500 char), 
    training_location              varchar2(100 char), 
    training_priority              number, 
    more_info                      varchar2(200 char),
    reason                         varchar2(4000 char),
    accepted                       number constraint cf_trainings_wishl_accepted_ck
                                   check (accepted IS NULL OR accepted in (0,1)),
    refusal_reason                 varchar2(4000 char),
    created_on                     date not null,
    created_by                     varchar2(255 char) not null,
    modified_on                    date not null,
    modified_by                    varchar2(255 char) not null
)
;

create index cf_trainings_wishl_i1 on cf_trainings_wishlist (employee_id);