create table cf_trainings (
    id                             number generated by default on null as identity 
                                   constraint cf_trainings_id_pk primary key,
    title                          varchar2(500 char),
    more_info                      varchar2(4000 char),
    training_cost                  number,
    created_on                     date not null,
    created_by                     varchar2(255 char) not null,
    modified_on                    date not null,
    modified_by                    varchar2(255 char) not null
)
;