create table cf_trainings_dates (
    id                             number generated by default on null as identity 
                                   constraint cf_trainings_dates_id_pk primary key,
    training_id                    number
                                   constraint cf_trainings_da_training_id_fk
                                   references cf_trainings on delete cascade,
    start_date                     date,
    end_date                       date,
    status                         number 
                                   constraint cf_training_dates_status_fk
                                   references cf_lov_values,
    created_on                     date not null,
    created_by                     varchar2(255 char) not null,
    modified_on                    date not null,
    modified_by                    varchar2(255 char) not null
)
;

create index cf_trainings_dates_i1 on cf_trainings_dates (training_id);