create table cf_training_employees (
    id                             number generated by default on null as identity 
                                   constraint cf_training_employ_id_pk primary key,
    training_id                    number
                                   constraint cf_training_emp_training_id_fk
                                   references cf_trainings on delete cascade,
    employee_id                    number
                                   constraint cf_training_emp_employee_id_fk
                                   references cf_employees on delete cascade,
    completed_on                   date,
    created_on                     date not null,
    created_by                     varchar2(255 char) not null,
    modified_on                    date not null,
    modified_by                    varchar2(255 char) not null
)
;

create index cf_training_employ_i1 on cf_training_employees (employee_id);
create index cf_training_employ_i142 on cf_training_employees (training_id);